# Generated by Django 6.0.2 on 2026-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
