# Generated by Django 6.0.2 on 2026-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0004_alter_bug_assigned_to_alter_bug_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
