# Generated by Django 6.0.2 on 2026-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0005_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
