# Generated by Django 6.0.2 on 2026-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
