# Generated by Django 6.0.2 on 2026-02-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0010_project_logo_project_short_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='member',
            new_name='members',
        ),
    ]
