# Generated by Django 6.0.2 on 2026-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0011_rename_member_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], default='Feature', max_length=10),
        ),
    ]
