# Generated by Django 6.0.2 on 2026-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0012_alter_bug_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
